import { createFileRoute } from "@tanstack/react-router";
import { AlertOctagon, CloudRain, Construction, ShieldCheck, Siren, Users } from "lucide-react";
import { Shell } from "@/components/safepath/Shell";
import { useApp } from "@/lib/app-state";
import { AI_NOTIFICATIONS } from "@/data/safepath";

export const Route = createFileRoute("/notifications")({
  head: () => ({
    meta: [
      { title: "AI Notifications Centre — SafePath AI" },
      {
        name: "description",
        content:
          "Weather warnings, accident reports, crime advisories, road closures and police alerts generated by SafePath AI.",
      },
      { property: "og:title", content: "AI Notifications Centre — SafePath AI" },
      {
        property: "og:description",
        content: "Proactive safety notifications for every journey.",
      },
    ],
  }),
  component: NotificationsPage,
});

const ICON = {
  weather: CloudRain,
  safety: AlertOctagon,
  traffic: Construction,
  police: ShieldCheck,
  crowd: Users,
  emergency: Siren,
};

const COLOR = {
  weather: "var(--color-primary)",
  safety: "var(--color-danger)",
  traffic: "var(--color-warn)",
  police: "var(--color-safe)",
  crowd: "var(--color-warn)",
  emergency: "var(--color-danger)",
};

function NotificationsPage() {
  const { t } = useApp();
  return (
    <Shell>
      <div className="space-y-4">
        <div>
          <h1 className="font-display text-xl font-bold">{t.notifications}</h1>
          <p className="text-xs text-muted-foreground">
            {AI_NOTIFICATIONS.length} AI-generated alerts · updated live
          </p>
        </div>
        {AI_NOTIFICATIONS.map((n, i) => {
          const Icon = ICON[n.kind];
          const col = COLOR[n.kind];
          return (
            <div
              key={n.id}
              className="animate-rise flex gap-3 rounded-3xl border bg-card p-4 shadow-soft"
              style={{ animationDelay: `${i * 45}ms` }}
            >
              <span
                className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl"
                style={{ background: `color-mix(in oklab, ${col} 16%, transparent)` }}
              >
                <Icon className="h-5 w-5" style={{ color: col }} />
              </span>
              <div className="min-w-0 flex-1">
                <div className="flex items-start justify-between gap-2">
                  <p className="text-sm font-bold">{n.title}</p>
                  <span className="shrink-0 text-[0.62rem] font-semibold text-muted-foreground">
                    {n.minutesAgo < 60 ? `${n.minutesAgo}m` : `${Math.round(n.minutesAgo / 60)}h`}
                  </span>
                </div>
                <p className="mt-1 text-xs leading-relaxed text-muted-foreground">{n.body}</p>
              </div>
            </div>
          );
        })}
      </div>
    </Shell>
  );
}
